### ISSUE TITLE
Is the github.com/pkg/errors dependency still desired?

### ISSUE THREAD

**Issue by kevinmichaelchen** [lzap/cloudwatchwriter2#2]
Hey 👋🏼 Thanks for [forking](https://github.com/mec07/cloudwatchwriter) this!

My team is considering CloudWatch, and this project looks great.

I was wondering if we could trim down the dependency tree even further!

The `pkg/errors` package was [archived](https://github.com/pkg/errors) a while ago, and error wrapping has been [natively supported](https://go.dev/blog/go1.13-errors) since Go 1.13.

If that all sounds reasonable, I can put up a PR.

**Comment by lzap** [comment]
Absolutely, I just blindly forked without any more cleanup ambitions but I am all for improving the codebase. This is now deployed in production and it works well.

I was on vacation but normally I reply much quicker, looking forward a PR :-)

**Comment by lzap** [comment]
You know what...

https://github.com/lzap/cloudwatchwriter2/commit/62014e9bf33816af5cd23e1c5eae8d1579ee4dd1

Do you want to see a release? I can cut v1.2 I think.
